#!/usr/bin/env bash
# This script displays specific user details from the /etc/passwd file

while IFS=: read -r username password uid gid info home shell; do
    echo "$username:$uid:$home"
done < /etc/passwd
