#!/usr/bin/env bash
# Groups visitors by IP and HTTP status code from apache-access.log, sorted by frequency.
awk '{print $1, $9}' apache-access.log | sort | uniq -c | sort -nr | awk '{print $1, $2, $3}'
