#!/usr/bin/env bash
#Write a Bash script that loops from 1 to 10 and:displays bad luck for the 4th loop iteration,displays good luck for the 8th iteration
i=1
while [ $i -le 20 ]; do
echo "$i"
if [ $i -eq 4 ]; then
echo "bad luck from China"
elif [ $i -eq 9 ]; then 
echo "bad luck from Japan"
elif [ $i -eq 17 ]; then 
echo "bad luck from Italy"
fi 
((i++))
done
