#!/usr/bin/env bash
# This script displays hours and minutes in the exact required format

hour=0
while [ $hour -le 12 ]
do
    # This must be OUTSIDE the minute loop
    echo "Hour: $hour"
    
    minute=1
    while [ $minute -le 59 ]
    do
        echo "$minute"
        ((minute++))
    done
    
    ((hour++))
done
